{{- $values := .Values -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrets-server
  name: secrets-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: secrets-server
        should_scrape: scrape
    spec:
      containers:
      - env:
        - name: CONFIGS
          value: {{ (.Files.Get "../configs.jsonc" | replace "\n" " " | quote) }}
        image: {{ $values.image }}
        name: secrets-server
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
